apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: node
  namespace: demo-production
spec:
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: node-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: demo
              password: demo
              rootPassword: demo
              username: demo
            global:
              storageClass: linode-block-storage
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 100Mi
  affinity: {}
  autodeploy: true
  autoscale: false
  autoscaling:
    enabled: false
  branch: main
  buildpack: NodeJS
  cronjobs: []
  deploymentstrategy: git
  domain: node.demo.kubero.dev
  envVars:
  - name: MYSQL_USER
    value: demo
  - name: MYSQL_PATH
    value: demo
  - name: MYSQL_HOST
    value: node-mysql
  - name: MYSQL_PORT
    value: "3306"
  extraVolumes: []
  fullnameOverride: ""
  gitrepo:
    admin: false
  image:
    build:
      command: npm install
      repository: node
      tag: latest
    containerPort: 8080
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: main
    pullPolicy: Always
    repository: ghcr.io/kubero-dev/template-nodeapp
    run:
      command: node index.js
      repository: node
      securityContext:
        readOnlyRootFilesystem: true
      tag: latest
    tag: latest
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: nginx
    enabled: true
    hosts:
    - host: node.demo.kubero.dev
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  name: node
  nameOverride: ""
  nodeSelector: {}
  phase: production
  pipeline: demo
  podAnnotations: {}
  podSecurityContext: {}
  podsize:
    default: true
    description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
    name: small
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 0.5Gi
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 0.5Gi
  service:
    port: 80
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  tolerations: []
  vulnerabilityscan:
    enabled: false
    image:
      repository: aquasec/trivy
      tag: latest
    schedule: 6 8 * * *
  web:
    autoscaling:
      maxReplicas: 3
      minReplicas: 1
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    replicaCount: 1
  worker:
    autoscaling:
      maxReplicas: 0
      minReplicas: 0
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
    replicaCount: 0